### ISSUE TITLE
Not launching - Old library

### ISSUE THREAD

**Issue by UltraBlackLinux** [wwmm/fastgame#3]
Hey there,
I am having some problems with launching fastgame: `fastgame: error while loading shared libraries: libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory`
When listing the /usr/lib directory, the library now has the version 1.76.0, so please update FG!
Thanks!

**Comment by wwmm** [comment]
>When listing the /usr/lib directory, the library now has the version 1.76.0, so please update FG!

Usually when this `boost` error happens recompiling the package is enough to fix the problem. It happens to other AUR packages that depend on the Boost Library too.

**Comment by wwmm** [comment]
If you are an Arch Linux user it is just a matter of reinstalling the AUR package. Every time Boost is upgraded this has to be done. It is annoying but it I am not aware of another way to deal with this.

**Comment by UltraBlackLinux** [comment]
> If you are an Arch Linux user it is just a matter of reinstalling the AUR package. Every time Boost is upgraded this has to be done. It is annoying but it I am not aware of another way to deal with this.

Oh lovely, that worked! I previoisly downloaded the package from the chaotic aur, so I guess they have a faulty package

**Comment by jarrard** [comment]
Doesn't work for me, insists on v1.75 no matter how many times I rebuild it, or delete and rebuild! 

EDIT: AUR/Repo is a bin version not built. Still getting theme errors and such when building myself.. no idea

Figured it out in the end. But yeah all the arch repo's are pre-configured for older boost version.. oops
