### ISSUE TITLE
NVIDIA section's "Mode" option is empty

### ISSUE THREAD

**Issue by NaterEST** [wwmm/fastgame#7]
As the title says. I have a GTX 980, and in the previous version of the fastgame launcher's UI the "Mode" section showed different performance modes for the GPU. Now that option is just empty.

**Comment by NaterEST** [comment]
![image](https://github.com/wwmm/fastgame/assets/76655321/c498b164-2e39-4392-9255-d36f46ca782b)

**Comment by wwmm** [comment]
Thanks for reporting this bug. As I switched from nvidia to amd a few years ago catching these kind of problems became harder. I've updated our master branch. Let me know if this fixed the issue.

**Comment by NaterEST** [comment]
yup, just tested it and I could switch to Maximum Performance
